[package]
name = "gravity-simulation"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
async-std = "1.12.0"
ellipsoid = "0.1.6"
rayon = "1.7.0"

